    drop table if exists timer;
    create table timer (
       timer_id bigint generated by default as identity,
        content varchar(255),
        continuous_count integer,
        end_time timestamp,
        is_finish boolean,
        start_time timestamp,
        member_id bigint not null,
        planner_id bigint,
        primary key (timer_id)
    )
